# Generated by Django 5.0.3 on 2024-03-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ipaddresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddresses',
            name='host',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='ipaddresses',
            name='range',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='ipaddresses',
            name='subnet',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
