# Generated by Django 5.0.3 on 2024-03-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ipaddresses_host_alter_ipaddresses_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddresses',
            name='host',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddresses',
            name='range',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddresses',
            name='subnet',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
