# Generated by Django 5.0.3 on 2024-03-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ipaddresses_host_alter_ipaddresses_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddresses',
            name='frequency',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
