# Generated by Django 5.0.3 on 2024-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ipaddresses_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='credentials',
            name='community',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
