# Generated by Django 5.0.3 on 2024-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_credentials_device_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
