# Generated by Django 5.0.3 on 2024-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_credentials_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='enable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
