# Generated by Django 5.0.3 on 2024-03-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ipaddresses_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddresses',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
