# Generated by Django 5.0.3 on 2024-04-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_device_device_model_alter_device_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
