# Generated by Django 5.0.3 on 2024-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_device_description_device_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=50, unique=True)),
                ('vendor', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
    ]
